# User config
author: "Jake Hyunseong Yang"
tagline: "Pineapple Certfied Jekyll Theme"
description: "You miss 100% of the shots you don't take. –Wayne Gretzky.<br><br>
Drawing Generative Arts with p5.js, please enjoy!"
keywords: "Generative Arts"
email: "yanghyunsung322@gmail.com"

linkedin: "https://www.linkedin.com/in/jakehyunseong/"
twitter: "https://x.com/99hyu99"
github: "https://github.com/jake-yang"
youtube: "https://www.youtube.com/@WhimsyWealth-y9w"
note: "https://note.com/nomorecoffee"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
